image: maven:latest

stages:
  - build
  - test

# Build
build:data-scraper:
  stage: build
  script:
    - cd data-scraper
    - mvn clean install

build:neo4j-data-access:
  stage: build
  script:
    - cd neo4j-data-access
    - mvn clean install

# Test
test:data-scraper:
  stage: test
  needs: ["build:data-scraper"]
  script:
    - cd data-scraper
    - mvn test

test:neo4j-data-access:
  stage: test
  needs: ["build:neo4j-data-access"]
  script:
    - cd neo4j-data-access
    - mvn test
