# TODO: use custom docker image to prevent multiple dependency imports
image: maven:latest

stages:
  - build
  - test

# Build
build:user-db:
  stage: build
  script:
    - cd user-db
    - mvn clean package -DskipTests

build:data-scraper:
  stage: build
  script:
    - cd data-scraper
    - mvn clean package -DskipTests

build:neo4j-data-access:
  stage: build
  script:
    - cd neo4j-data-access
    - mvn clean package -DskipTests

# TODO: FE

# Test
test:user-db:
  stage: test
  needs: ["build:user-db"]
  script:
    - cd user-db
    - mvn test
  artifacts:
    paths:
      - user-db/target/user-db-*.jar

test:data-scraper:
  stage: test
  needs: ["build:data-scraper"]
  script:
    - cd data-scraper
    - mvn test
  artifacts:
    paths:
      - user-db/target/data-scraper-*.jar

test:neo4j-data-access:
  stage: test
  needs: ["build:neo4j-data-access"]
  script:
    - cd neo4j-data-access
    - mvn test
  artifacts:
    paths:
      - user-db/target/neo4j-data-access-*.jar

# TODO: FE

# Deploy
# TODO: Deploy Jars
