services:

  neo4j:
    container_name: neo4j
    image: neo4j:2025.04.0
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_server_memory_heap_initial__size=2G
      - NEO4J_server_memory_heap_max__size=2G
    volumes:
      - ./neo4j_db/data:/data
      - ./neo4j_db/logs:/logs
      - ./neo4j_db/import:/var/lib/neo4j/import
      - ./neo4j_db/plugins:/plugins

  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage

  #production
  # frontend:
    # container_name: frontend
    # build: ./frontend
    # image: frontend:latest
    # ports:
      # - 4200:4200

  #for development only
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    working_dir: /app
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  user-db:
    container_name: user-db
    build: ./user-db
    ports:
      - "8090:8090"
  orchestrator:
    container_name: orchestrator
    build: ./orchestrator
    ports:
      - "9098:9098"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    environment:
      - USER_DB_URL=http://user-db:8090
      - NEO4J_DATA_ACCESS_URL=http://neo4j-data-access:8083
      - JWT_SECRET=CNLhuS70KdmqBduY1qYM5Q/fKOLySiD/yYr2Qz0c2GJ9LNVgMarMX4CrU2mkyy8qZobBFA3JglypiPTxg/P7aA==
    depends_on:
      - user-db
      - neo4j-data-access

  neo4j-data-access:
    container_name: neo4j-data-access
    build: ./neo4j-data-access
    ports:
      - "8083:8083"
    environment:
      - neo4j.url=bolt://neo4j:7687

  qdrant-adapter:
    container_name: qdrant-adapter
    build: ./qdrant-adapter
    ports:
      - "8081:8081"

  openai-adapter:
    container_name: openai-adapter
    build: ./openai-adapter
    ports:
      - "8088:8088"
    environment:
      - OPENAI_API_KEY=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
